// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfOozqRb6aZPGBygAIxr6OZ9S04XZkwGU',
    appId: '1:312108519586:web:acb18ca6079f4f36e0c7fb',
    messagingSenderId: '312108519586',
    projectId: 'connekta-flutter-app',
    authDomain: 'connekta-flutter-app.firebaseapp.com',
    storageBucket: 'connekta-flutter-app.appspot.com',
    measurementId: 'G-H92FG4PY6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6PJRNR_hUlF4r5Vp8cHMG_lSN2SZh6J4',
    appId: '1:312108519586:android:4ce3fc1645b8d3ece0c7fb',
    messagingSenderId: '312108519586',
    projectId: 'connekta-flutter-app',
    storageBucket: 'connekta-flutter-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANrCmNffTFgktNvckhnXP_ROpfNmRRCXo',
    appId: '1:312108519586:ios:42431377b22eb6d3e0c7fb',
    messagingSenderId: '312108519586',
    projectId: 'connekta-flutter-app',
    storageBucket: 'connekta-flutter-app.appspot.com',
    iosBundleId: 'com.example.connekta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANrCmNffTFgktNvckhnXP_ROpfNmRRCXo',
    appId: '1:312108519586:ios:a253ed3130828f84e0c7fb',
    messagingSenderId: '312108519586',
    projectId: 'connekta-flutter-app',
    storageBucket: 'connekta-flutter-app.appspot.com',
    iosBundleId: 'com.example.connekta.RunnerTests',
  );
}
